export const contacts = [
    { id: 1, name: "Arjun" },
    { id: 2, name: "Kavi" },
    { id: 3, name: "Anjali" },
    { id: 4, name: "Priya" },
    { id: 5, name: "Vikram" },
    { id: 6, name: "Lakshmi" },
    { id: 69, name: "Vijay" },
    { id: 7, name: "Suresh" },
    { id: 8, name: "Nisha" },
    { id: 9, name: "Ravi" },
    { id: 10, name: "Deepa" },
    { id: 11, name: "Sanjay" },
    { id: 12, name: "Ganesh" },
    { id: 13, name: "Divya" },
    { id: 14, name: "Vani" },
    { id: 15, name: "Dala" },
    { id: 16, name: "Karthik" },
    { id: 17, name: "Meena" },
    { id: 18, name: "Surya" },
    { id: 19, name: "Uma" },
    { id: 20, name: "Mohan" }
];